//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV_DataBasefirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public string MaSV { get; set; }
        public string TenSV { get; set; }
        public bool GioiTinh { get; set; }
        public Nullable<double> DiemTB { get; set; }
        public int MaLop { get; set; }
        public Nullable<bool> anh { get; set; }
        public Nullable<bool> hoso { get; set; }
        public Nullable<bool> cccd { get; set; }
    
        public virtual Lop Lop { get; set; }
    }
}
